<a href="https://colab.research.google.com/github/ndevkota12/Hierarchical-covariance-risk/blob/main/notebooks/01_synthetic_test_hierarchical_cov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

def hierarchical_covariance(S, tree_distances, lam):
    """
    Hierarchy-regularized covariance estimation using soft-thresholding.

    Solves:
        min ||Σ - S||_F^2 + λ Σ_{i≠j} d_T(i,j) |Σ_ij|

    Parameters
    ----------
    S : np.ndarray, shape (n,n)
        Sample covariance matrix.
    tree_distances : np.ndarray, shape (n,n)
        Ultrametric distance matrix d_T(i,j).
    lam : float
        Regularization strength.

    Returns
    -------
    Sigma_hat : np.ndarray, shape (n,n)
        Regularized covariance matrix.
    """
    n = S.shape[0]
    Sigma_hat = S.copy()

    for i in range(n):
        for j in range(n):
            if i != j:
                # soft-thresholding
                penalty = lam * tree_distances[i, j]
                if S[i, j] > penalty:
                    Sigma_hat[i, j] = S[i, j] - penalty
                elif S[i, j] < -penalty:
                    Sigma_hat[i, j] = S[i, j] + penalty
                else:
                    Sigma_hat[i, j] = 0.0
    return Sigma_hat

In [6]:
# Synthetic sample covariance (5 assets)
S = np.array([
    [0.04, 0.03, 0.02, 0.01, 0.01],
    [0.03, 0.05, 0.02, 0.01, 0.01],
    [0.02, 0.02, 0.03, 0.005, 0.005],
    [0.01, 0.01, 0.005, 0.02, 0.015],
    [0.01, 0.01, 0.005, 0.015, 0.025]
])

# Synthetic tree distances (ultrametric)
d_T = np.array([
    [0,1,2,3,3],
    [1,0,2,3,3],
    [2,2,0,3,3],
    [3,3,3,0,1],
    [3,3,3,1,0]
])

lam = 0.01

Sigma_hat = hierarchical_covariance(S, d_T, lam)
print("Original S:\n", S)
print("\nRegularized Sigma_hat:\n", Sigma_hat)

Original S:
 [[0.04  0.03  0.02  0.01  0.01 ]
 [0.03  0.05  0.02  0.01  0.01 ]
 [0.02  0.02  0.03  0.005 0.005]
 [0.01  0.01  0.005 0.02  0.015]
 [0.01  0.01  0.005 0.015 0.025]]

Regularized Sigma_hat:
 [[0.04  0.02  0.    0.    0.   ]
 [0.02  0.05  0.    0.    0.   ]
 [0.    0.    0.03  0.    0.   ]
 [0.    0.    0.    0.02  0.005]
 [0.    0.    0.    0.005 0.025]]
